//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyTitle("BLTAdoptAHero")]
[assembly: AssemblyVersion("5.3.1")]
[assembly: AssemblyFileVersion("5.3.1")]

// Generated by the MSBuild WriteCodeFragment class.

